name: Check Changelog

on:
  pull_request:
    types: [opened, reopened, edited, labeled, unlabeled, synchronize]

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.head.ref, 'release-')
    steps:
      - uses: actions/checkout@v4
      - name: Check that CHANGELOG is touched
        run: |
          git fetch origin ${{ github.base_ref }} --depth 1 && \
          git diff remotes/origin/${{ github.base_ref }} --name-only | grep CHANGELOG.md
