name: Draft Release Branch

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Type of version bump (major, minor, patch)'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  draft-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Make scripts executable
        run: |
          chmod +x scripts/release/draft-release
          chmod +x scripts/release/update-changelog

      - name: Run release script
        run: ./scripts/release/draft-release "${{ github.event.inputs.bump_type }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
