name: Publish to NPM and Change Management

on:
  workflow_run:
    workflows: ["Create Github Tag and Release"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: write
  actions: read
  id-token: write

jobs:
  check_for_moratorium:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: change_management
    steps:
      - uses: actions/checkout@v4
      - env:
          TPS_API_TOKEN: ${{ secrets.TPS_API_TOKEN_PARAM }}
        run: ./scripts/release/tps-check-lock heroku-applink-nodejs ${{ github.sha }}

  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: check_for_moratorium
    runs-on: ubuntu-latest
    environment: change_management
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Get workflow run ID
        id: get_workflow
        run: |
          echo "run_id=${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT

      - name: Download build artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir -p dist
          gh run download ${{ steps.get_workflow.outputs.run_id }} --name release-artifacts-main --dir dist/

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_RELEASE_AUTOMATION_TOKEN }}
